// Services/Web/React/todo/src/pages/home/home.tsx

import { useEffect, useState, useActionState } from 'react';
import './home.css';
import classNames from 'classnames';
import { type ITodoItem, type IClipboardItem, type ItemFilter } from '../../types';
import ApiService from '../../services/api';
import TodoItem from '../../components/todo-item/todo-item';
import { useSearchParams } from 'react-router-dom';
import { useSnackbar } from '../../components/snackbar/snackbar';
import { Paging } from '../../components/paging/paging';
import { ClipboardItem } from '../../components/clipboard-item/clipboard-item';
import { useMsal } from '@azure/msal-react';

const apiService = new ApiService();

function Home() {
  const { instance, accounts } = useMsal();
  const [clipboards, setClipboards] = useState<IClipboardItem[]>([]);
  const [items, setItems] = useState<ITodoItem[]>([]);
  const [selectedClipboardId, setSelectedClipboardId] = useState<number | null>(null);
  const [selectedItemFilter, setSelectedItemFilter] = useState<ItemFilter>('ALL');
  const [editingItemId, setEditingItemId] = useState<number | null>(null);
  const [editingClipboardId, setEditingClipboardId] = useState<number | null>(null);
  const [editedClipboardName, setEditedClipboardName] = useState<string>('');
  const [currentPage, setCurrentPage] = useState<number>(1);
  const itemsPerPage = 10;
  const [searchParams, setSearchParams] = useSearchParams();
  const showSnackbar = useSnackbar();

  // Set MSAL instance and fetch clipboards when instance is ready or authentication changes
  useEffect(() => {
    apiService.setMsalInstance(instance);
    apiService.fetchClipboards().then(setClipboards);
  }, [instance, accounts]);

  // Load items after clipboards are available or when URL params change
  useEffect(() => {
    const clipboardParam = searchParams.has('clipboard') ? Number(searchParams.get('clipboard')) : null;
    const itemFilterParam = searchParams.has('itemFilter') ? searchParams.get('itemFilter') : 'ALL';
    const pageParam = searchParams.has('page') ? Number(searchParams.get('page')) : 1;

    setSelectedClipboardId(clipboardParam);
    setSelectedItemFilter(itemFilterParam as ItemFilter);
    setCurrentPage(pageParam > 0 ? pageParam : 1);

    var clipbloardId = clipboardParam ?? (clipboards.length > 0 ? clipboards[0].id : null);

    if (clipboardParam === null && clipboards.length > 0) {
      setSearchParams(`?clipboard=${clipboards[0].id}`);
    }

    if (clipbloardId !== null) {
      apiService.fetchItems(clipbloardId).then(setItems);
    }
  }, [clipboards, searchParams]);

  const filteredItems = items.filter(item => {
    if (selectedItemFilter === 'ALL') return true;
    if (selectedItemFilter === 'COMPLETED') return item.isComplete;
    if (selectedItemFilter === 'UNFINISHED') return !item.isComplete;
    return true;
  });

  const totalPages = Math.ceil(filteredItems.length / itemsPerPage);
  
  const pagedItems = filteredItems.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  );

  const changeClipboard = (clipboardId: number) => {
    console.log('Selected clipboard ID:', clipboardId);
    setSelectedClipboardId(clipboardId);
    setCurrentPage(1);
    const newSearchParams = new URLSearchParams(searchParams);
    newSearchParams.set('clipboard', clipboardId.toString());
    newSearchParams.delete('page'); // Reset to page 1 when changing clipboards
    setSearchParams(newSearchParams, { replace: true });

    apiService.fetchItems(clipboardId).then(setItems);
  }

  const changeItemFilter = (itemFilter: ItemFilter) => {
    setSelectedItemFilter(itemFilter);
    setCurrentPage(1);
    const newSearchParams = new URLSearchParams(searchParams);
    newSearchParams.set('itemFilter', itemFilter);
    newSearchParams.delete('page'); // Reset to page 1
    setSearchParams(newSearchParams, { replace: true });
  }

  const handlePageChange = (page: number) => {
    setCurrentPage(page);
    const newSearchParams = new URLSearchParams(searchParams);
    if (page > 1) {
      newSearchParams.set('page', page.toString());
    } else {
      newSearchParams.delete('page');
    }
    setSearchParams(newSearchParams, { replace: true });
  }

  const hasClipboards = () => {
    return clipboards.length > 0;
  }

  const clipboardSelectorCls = classNames('clipboard-selector', {
    'disabled': !hasClipboards(),
  })

  const itemsSectionCls = classNames('items-section', {
    'disabled': !hasClipboards(),
  })

  const handleTodoItemComplete = (id: number) => {
    const item = items.find(i => i.id === id);
    if (!item) return;

    if (!item.isComplete) {
      apiService.completeItem(id)
      .then((response) => {
        if (!response.ok) {
          console.error('Error completing item:', response);
          showSnackbar('Failed to complete item', { isError: true });
          return;
        }
        setItems(items.map(i => 
          i.id === id ? { ...i, isComplete: !i.isComplete } : i
        ));
        showSnackbar('Item completed successfully!');
      })
      .catch((error) => {
        console.error('Error completing item:', error);
        showSnackbar('Failed to complete item', { isError: true });
      });
    } else {
      apiService.unfinishItem(id)
      .then((response) => {
        if (!response.ok) {
          console.error('Error setting item as unfinished:', response);
          showSnackbar('Failed to set item as unfinished', { isError: true });
          return;
        }
        setItems(items.map(i => 
          i.id === id ? { ...i, isComplete: !i.isComplete } : i
        ));
        showSnackbar('Item set to unfinished.');
      })
      .catch((error) => {
        console.error('Error setting item as unfinished:', error);
        showSnackbar('Failed to set item as unfinished', { isError: true });
      });
    }
  };

  const handleTodoItemDelete = (id: number) => {
    apiService.deleteItem(id)
    .then((response) => {
      if (!response.ok) {
        console.error('Error deleting item:', response);
        showSnackbar('Failed to delete item', { isError: true });
        return;
      }
      setItems(items.filter(i => i.id !== id));
      // Clear editing state if the deleted item was being edited
      if (editingItemId === id) {
        setEditingItemId(null);
      }
      showSnackbar('Item deleted successfully!');
    })
    .catch((error) => {
      console.error('Error deleting item:', error);
      showSnackbar('Failed to delete item', { isError: true });
    });
  };

  const handleTodoItemSave = (id: number, name: string) => {
    apiService.editItem(id, name)
    .then((response) => {
      if (!response.ok) {
        console.error('Error updating item:', response);
        showSnackbar('Failed to update item', { isError: true });
        return;
      }
      setItems(items.map(i => 
        i.id === id ? { ...i, name } : i
      ));
      setEditingItemId(null);
      showSnackbar('Item updated successfully!');
    })
    .catch((error) => {
      console.error('Error updating item:', error);
      showSnackbar('Failed to update item', { isError: true });
    });
  };

  const handleTodoItemEdit = (id: number) => {
    setEditingItemId(id);
  };

  const handleTodoItemCancelEdit = () => {
    setEditingItemId(null);
  };

  const handleClipboardDelete = (id: number) => {
    const hasItems = selectedClipboardId === id && items.length > 0;
    const unfinishedCount = selectedClipboardId === id ? items.filter(item => !item.isComplete).length : 0;
    
    // This messaging can be improved further by retrieving item count for the clipboard to be deleted without loading all items
    let message = 'Are you sure you want to delete this clipboard?';
    if (hasItems) {
      message = unfinishedCount > 0
        ? `Are you sure you want to delete this clipboard? All items in it will be deleted (${unfinishedCount} unfinished).`
        : 'Are you sure you want to delete this clipboard? All items in it will be deleted.';
    }
    
    if (!window.confirm(message)) {
      return;
    }

    apiService.deleteClipboard(id)
      .then((response) => {
        if (!response.ok) {
          console.error('Error deleting clipboard:', response);
          showSnackbar('Failed to delete clipboard', { isError: true });
          return;
        }
        
        // Clear editing state if the deleted clipboard was being edited
        if (editingClipboardId === id) {
          setEditingClipboardId(null);
          setEditedClipboardName('');
        }
        
        const updatedClipboards = clipboards.filter(c => c.id !== id);
        
        // Clear items immediately to prevent showing stale data
        if (selectedClipboardId === id) {
          setItems([]);
        }
        
        // Update URL and clipboards state - let useEffect handle fetching
        if (selectedClipboardId === id) {
          const newSearchParams = new URLSearchParams(searchParams);
          
          if (updatedClipboards.length > 0) {
            // Select the first clipboard and update URL
            const firstClipboardId = updatedClipboards[0].id;
            setSelectedClipboardId(firstClipboardId);
            newSearchParams.set('clipboard', firstClipboardId.toString());
            setSearchParams(newSearchParams, { replace: true });
          } else {
            // No clipboards left
            setSelectedClipboardId(null);
            newSearchParams.delete('clipboard');
            setSearchParams(newSearchParams, { replace: true });
          }
        }
        
        // Update clipboards state - this will trigger useEffect to fetch items
        setClipboards(updatedClipboards);
        
        showSnackbar('Clipboard deleted successfully!');
      })
      .catch((error) => {
        console.error('Error deleting clipboard:', error);
        showSnackbar('Failed to delete clipboard', { isError: true });
      });
  };

  const handleClipboardNameChange = (id: number, name: string) => {
    setEditedClipboardName(name);
  };

  const handleClipboardSave = (id: number, name: string) => {
    apiService.editClipboard(id, name)
      .then((response) => {
        if (!response.ok) {
          console.error('Error updating clipboard:', response);
          showSnackbar('Failed to update clipboard', { isError: true });
          return;
        }
        setClipboards(clipboards.map(c => c.id === id ? { ...c, name } : c));
        showSnackbar('Clipboard updated successfully!');
        setEditingClipboardId(null);
        setEditedClipboardName('');
      })
      .catch((error) => {
        console.error('Error updating clipboard:', error);
        showSnackbar('Failed to update clipboard', { isError: true });
      });
  };

  // Todo form action
  const addTodoItemAction = async (_prevState: any, formData: FormData) => {
    const name = formData.get('name') as string;

    // Validate clipboard is selected
    if (!selectedClipboardId) {
      return { success: false, error: 'Please select a clipboard first' };
    }

    // Validate name is not empty or whitespace
    if (!name || name.trim().length === 0) {
      return { success: false, error: 'Todo item name is required and cannot be only whitespace' };
    }

    try {
      const response = await apiService.addItem(selectedClipboardId, name);
      
      if (!response.ok) {
        console.error('Error adding item:', response);
        showSnackbar('Failed to add item', { isError: true });
        return { success: false, error: 'Failed to add item. Please try again.' };
      }

      const newItem = await response.json();
      
      // Update items list
      setItems([...items, newItem]);

      showSnackbar('Item added successfully!');
      return { success: true, error: null };
    } catch (error) {
      console.error('Error adding item:', error);
      showSnackbar('Failed to add item', { isError: true });
      return { success: false, error: 'Failed to add item. Please try again.' };
    }
  };

  const [formState, formAction, isPending] = useActionState(addTodoItemAction, { success: false, error: null });

  // Clipboard form action
  const addClipboardAction = async (_prevState: any, formData: FormData) => {
    const name = formData.get('name') as string;

    // Validate name is not empty or whitespace
    if (!name || name.trim().length === 0) {
      return { success: false, error: 'Clipboard name is required and cannot be only whitespace' };
    }

    return apiService.addClipboard(name)
      .then(async (response) => {
        if (!response.ok) {
          console.error('Error adding clipboard:', response);
          showSnackbar('Failed to add clipboard', { isError: true });
          return Promise.resolve({ success: false, error: 'Failed to add clipboard. Please try again.' });
        }

        const newClipboard = await response.json();
        // Update clipboards list
        setClipboards([...clipboards, newClipboard]);
        // Select the new clipboard
        setSelectedClipboardId(newClipboard.id);
        const newSearchParams = new URLSearchParams(searchParams);
        newSearchParams.set('clipboard', newClipboard.id.toString());
        setSearchParams(newSearchParams, { replace: true });
        // Load items for the new clipboard
        apiService.fetchItems(newClipboard.id).then(setItems);
        showSnackbar('Clipboard added successfully!');
        return { success: true, error: null };
      })
      .catch((error) => {
        console.error('Error adding clipboard:', error);
        showSnackbar('Failed to add clipboard', { isError: true });
        return { success: false, error: 'Failed to add clipboard. Please try again.' };
      });
  };

  const [clipboardFormState, clipboardFormAction, isClipboardPending] = useActionState(addClipboardAction, { success: false, error: null });

  return (
    <>
      <div className="home-container">
        <h1>Todo List</h1>

          <div className={clipboardSelectorCls}>
            <label>
              Select Clipboard:
              <select disabled={!hasClipboards()} value={selectedClipboardId ?? ''} onChange={(e) => changeClipboard(Number(e.target.value))}>
                {clipboards.map((clipboard: IClipboardItem) => (
                  <option
                    key={clipboard.id}
                    value={clipboard.id}
                  >
                    {clipboard.name}
                  </option>
                ))
                }
              </select>
            </label>
          </div>

          <div className={itemsSectionCls}>
            <div className="filter-buttons">
              <button 
                onClick={() => changeItemFilter('ALL')}
                className={selectedItemFilter === 'ALL' ? 'active' : ''}
              >
                All {items.length}
              </button>
              <button 
                onClick={() => changeItemFilter('UNFINISHED')}
                className={selectedItemFilter === 'UNFINISHED' ? 'active' : ''}
              >
                Unfinished {items.filter(item => !item.isComplete).length}
              </button>
              <button 
                onClick={() => changeItemFilter('COMPLETED')}
                className={selectedItemFilter === 'COMPLETED' ? 'active' : ''}
              >
                Completed {items.filter(item => item.isComplete).length}
              </button>
            </div>

            {pagedItems.map((item: ITodoItem) => (
              <TodoItem
                key={item.id}
                item={item}
                editingItemId={editingItemId}
                onComplete={handleTodoItemComplete}
                onEdit={handleTodoItemEdit}
                onCancelEdit={handleTodoItemCancelEdit}
                onSave={handleTodoItemSave}
                onDelete={handleTodoItemDelete}
              />
            ))}

            <Paging
              currentPage={currentPage}
              totalPages={totalPages}
              onPageChange={handlePageChange}
            />
          </div>

          <div className="forms-container">
            <div className="new-todo-container">
              <form className="todo-form" action={formAction}>
                <div>
                  <label>To Do:</label>
                  <textarea name="name" disabled={!hasClipboards() || isPending}></textarea>
                  
                  {formState.error && (
                    <ul className="error-list">
                      <li>{formState.error}</li>
                    </ul>
                  )}
                </div>

                <button type="submit" disabled={!hasClipboards() || isPending}>
                  {isPending ? 'Adding...' : 'Add New Todo Item'}
                </button>
              </form>
            </div>
            <div className="clipboard-container">
              <label className="clipboard-label">Manage Clipboards:</label>
              <div className="clipboard-list">
                {clipboards.map((clipboard: any) => (
                  <ClipboardItem
                    id={clipboard.id}
                    name={clipboard.name}
                    isSelected={clipboard.id === selectedClipboardId}
                    editingClipboardId={editingClipboardId}
                    onEditingChange={setEditingClipboardId}
                    onDelete={handleClipboardDelete}
                    onNameChange={handleClipboardNameChange}
                  />
                ))}
              </div>
              <button 
                className="save-clipboard-button" 
                onClick={() => {
                  if (editingClipboardId !== null && editedClipboardName.trim()) {
                    handleClipboardSave(editingClipboardId, editedClipboardName.trim());
                  }
                }}
                style={{ display: editingClipboardId === null ? 'none' : 'block' }}
                disabled={!editedClipboardName.trim() || editedClipboardName === clipboards.find(c => c.id === editingClipboardId)?.name}
              >
                Save
              </button>

              <hr/>

              <form className="new-clipboard-form" action={clipboardFormAction}>
                <div>
                  <label>
                    New Clipboard Name:
                    <input type="text" name="name" disabled={isClipboardPending} />
                  </label>

                  {clipboardFormState.error && (
                    <ul className="error-list">
                      <li>{clipboardFormState.error}</li>
                    </ul>
                  )}
                </div>

                <button type="submit" disabled={isClipboardPending}>
                  {isClipboardPending ? 'Adding...' : 'Add Clipboard'}
                </button>
              </form>
            </div>
          </div>
      </div>
    </>
  )
}

export default Home;

// Services/Web/Angular/todo/src/app/pages/home/home.ts
import { Component, inject, signal, ChangeDetectionStrategy, OnInit, OnDestroy, computed } from '@angular/core';
import { TodoItem } from '../../components/todo-item/todo-item';
import { ClipboardItem } from '../../components/clipboard-item/clipboard-item';
import { DataSource } from '../../services/data-source';
import { CommonModule } from '@angular/common';
import { form, Field, required } from '@angular/forms/signals';
import { Snackbar } from '../../services/snackbar';
import { HttpErrorResponse } from '@angular/common/http';
import { Router, ActivatedRoute } from '@angular/router';
import { Paging } from '../../components/paging/paging';

interface NewTodoItemData {
  name: string;
}

interface NewClipboardData {
  name: string;
}

@Component({
  selector: 'app-home',
  imports: [TodoItem, ClipboardItem, Paging, CommonModule, Field],
  templateUrl: './home.html',
  styleUrl: './home.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})

export class Home implements OnInit, OnDestroy {

  // ========================================
  // Dependencies
  // ========================================
  private snackbar = inject(Snackbar);
  private dataSource = inject(DataSource);
  private router = inject(Router);
  private route = inject(ActivatedRoute);
  private routeSubscription?: any;
  private queryParamsSubscription?: any;

  // ========================================
  // Shared State
  // ========================================
  selectedClipboardId = signal<number | null>(null);
  filter = signal<'all' | 'completed' | 'unfinished'>('all');
  currentPage = signal<number>(1);
  itemsPerPage = 10;

  // ========================================
  // Todo Items State & Computed
  // ========================================
  items$ = signal<any[]>([]);
  editingItemId = signal<number | null>(null);

  newTodoItemModel = signal<NewTodoItemData>({
      name: '',
  });

  newTodoItemForm = form(this.newTodoItemModel, (schemaPath) => {
    required(schemaPath.name, { message: 'Name is required and cannot be only whitespace' });
  });

  filteredItems = computed(() => {
    const items = this.items$();
    const filterValue = this.filter();
    
    if (filterValue === 'completed') {
      return items.filter(item => item.isComplete);
    } else if (filterValue === 'unfinished') {
      return items.filter(item => !item.isComplete);
    }
    return items;
  });

  pagedItems = computed(() => {
    const filtered = this.filteredItems();
    const page = this.currentPage();
    const startIndex = (page - 1) * this.itemsPerPage;
    const endIndex = startIndex + this.itemsPerPage;
    return filtered.slice(startIndex, endIndex);
  });

  totalPages = computed(() => {
    return Math.ceil(this.filteredItems().length / this.itemsPerPage);
  });

  allItemsCount = computed(() => this.items$().length);
  
  completedItemsCount = computed(() => 
    this.items$().filter(item => item.isComplete).length
  );
  
  unfinishedItemsCount = computed(() => 
    this.items$().filter(item => !item.isComplete).length
  );

  // ========================================
  // Clipboard State & Computed
  // ========================================
  clipboards$ = signal<any[]>([]);
  editingClipboardId = signal<number | null>(null);
  editedClipboardName = signal<string>('');

  hasClipboards = computed(() => this.clipboards$().length > 0);

  newClipboardModel = signal<NewClipboardData>({
      name: '',
  });

  newClipboardForm = form(this.newClipboardModel, (schemaPath) => {
    required(schemaPath.name, { 
      message: 'Clipboard name is required and cannot be only whitespace'
    });
  });

  clipboardNameChanged = computed(() => {
    const editingId = this.editingClipboardId();
    if (editingId === null) return false;
    const clipboard = this.clipboards$().find(c => c.id === editingId);
    if (!clipboard) return false;
    return this.editedClipboardName() !== clipboard.name;
  });

  // ========================================
  // Lifecycle Hooks
  // ========================================
  ngOnInit() {
    this.queryParamsSubscription = this.route.queryParams.subscribe(params => {
      const filterParam = params['filter'];
      if (filterParam === 'completed' || filterParam === 'unfinished') {
        this.filter.set(filterParam);
      } else {
        this.filter.set('all');
      }

      const pageParam = params['page'];
      const page = pageParam ? Number(pageParam) : 1;
      this.currentPage.set(page > 0 ? page : 1);
    });
    
    this.routeSubscription = this.route.paramMap.subscribe(params => {
      const urlClipboardId = params.get('clipboardId');
      
      this.dataSource.fetchClipboards().subscribe(clipboards => {
        this.clipboards$.set(clipboards);
        this.handleClipboardRoute(urlClipboardId, clipboards);
      });
    });
  }

  ngOnDestroy() {
    this.routeSubscription?.unsubscribe();
    this.queryParamsSubscription?.unsubscribe();
  }

  // ========================================
  // Routing & Navigation
  // ========================================
  private handleClipboardRoute(urlClipboardId: string | null, clipboards: any[]) {
    if (urlClipboardId) {
      const clipboardId = Number(urlClipboardId);
      
      if (clipboards.some(c => c.id === clipboardId)) {
        this.selectedClipboardId.set(clipboardId);
        this.loadItemsForClipboard(clipboardId);
      } else if (clipboards.length > 0) {
        const currentFilter = this.filter();
        const page = this.currentPage();
        const queryParams: any = {};
        if (currentFilter !== 'all') queryParams.filter = currentFilter;
        if (page > 1) queryParams.page = page;
        this.router.navigate(['/clipboard', clipboards[0].id], { replaceUrl: true, queryParams });
      }
    } else if (clipboards.length > 0) {
      const currentFilter = this.filter();
      const page = this.currentPage();
      const queryParams: any = {};
      if (currentFilter !== 'all') queryParams.filter = currentFilter;
      if (page > 1) queryParams.page = page;
      this.router.navigate(['/clipboard', clipboards[0].id], { replaceUrl: true, queryParams });
    }
  }

  selectClipboard(clipboardId: number) {
    this.selectedClipboardId.set(clipboardId);
    
    const currentFilter = this.filter();
    const page = this.currentPage();
    const queryParams: any = {};
    if (currentFilter !== 'all') queryParams.filter = currentFilter;
    if (page > 1) queryParams.page = page;
    
    this.router.navigate(['/clipboard', clipboardId], { 
      queryParams
    });
    this.loadItemsForClipboard(clipboardId);
  }

  setFilter(filter: 'all' | 'completed' | 'unfinished') {
    this.filter.set(filter);
    this.currentPage.set(1);
    const clipboardId = this.selectedClipboardId();
    if (clipboardId) {
      const queryParams: any = {};
      if (filter !== 'all') queryParams.filter = filter;
      this.router.navigate(['/clipboard', clipboardId], { 
        queryParams
      });
    }
  }

  setPage(page: number) {
    this.currentPage.set(page);
    const clipboardId = this.selectedClipboardId();
    if (clipboardId) {
      const currentFilter = this.filter();
      const queryParams: any = {};
      if (currentFilter !== 'all') queryParams.filter = currentFilter;
      if (page > 1) queryParams.page = page;
      this.router.navigate(['/clipboard', clipboardId], { 
        queryParams
      });
    }
  }

  private adjustPageIfNeeded() {
    const currentPage = this.currentPage();
    const totalPages = this.totalPages();
    
    if (currentPage > totalPages && totalPages > 0) {
      this.setPage(totalPages);
    } else if (currentPage > 1 && this.pagedItems().length === 0 && this.filteredItems().length > 0) {
      this.setPage(Math.max(1, totalPages));
    }
  }

  // ========================================
  // Todo Items - Data Loading
  // ========================================
  loadItemsForClipboard(clipboardId: number) {
    this.dataSource.fetchItems(clipboardId).subscribe(items => {
      this.items$.set(items);
    });
  }

  // ========================================
  // Todo Items - Event Handlers
  // ========================================
  onAddTodoItem(event: Event) {
    event.preventDefault();
    const newTodoItem = this.newTodoItemModel();
    
    const clipboardId = this.selectedClipboardId();
    if (!clipboardId) {
      this.snackbar.openSnackBar('Please select a clipboard first', 'Close', true);
      return;
    }

    if (this.newTodoItemForm.name().invalid()) {
      this.newTodoItemForm.name().markAsTouched();
      return;
    }

    // Validate that the trimmed name is not empty
    if (newTodoItem.name.trim().length === 0) {
      this.snackbar.openSnackBar('Todo item name cannot be only whitespace', 'Close', true);
      return;
    }

    this.dataSource.addItem(clipboardId, newTodoItem.name).subscribe({
      next: (response) => {
        this.snackbar.openSnackBar('Item added successfully', 'Close');
        this.items$.set([...this.items$(), response]);
        this.resetTodoItemForm();
      },
      error: (error: HttpErrorResponse) => {
        this.snackbar.openSnackBar('Error adding item', 'Close', true);
        console.error('Error submitting data:', error);
        if (error.status === 400) {
          console.error('Invalid Request.');
        } else if (error.status === 500) {
          console.error('Server error.');
        } else {
          console.error('An unexpected error occurred.');
        }
      }
    });
  }

  onDeleteTodoItem(id: number) {
    this.dataSource.removeItem(id).subscribe({
      next: () => {
        this.snackbar.openSnackBar('Item deleted successfully', 'Close');
        this.items$.set(this.items$().filter(item => item.id !== id));
        this.adjustPageIfNeeded();
      },
      error: (error: HttpErrorResponse) => {
        this.snackbar.openSnackBar('Error deleting item', 'Close', true);
        console.error('Error deleting item:', error);
      }
    });
  }

  onCompleteTodoItem(id: number) {
    const item = this.items$().find(i => i.id === id);
    if (!item) return;

    const apiCall = item.isComplete 
      ? this.dataSource.unfinishItem(id) 
      : this.dataSource.completeItem(id);

    apiCall.subscribe({
      next: () => {
        this.snackbar.openSnackBar(
          item.isComplete ? 'Item marked as incomplete' : 'Item completed', 
          'Close'
        );
        this.items$.set(
          this.items$().map(i => 
            i.id === id ? { ...i, isComplete: !i.isComplete } : i
          )
        );
        this.adjustPageIfNeeded();
      },
      error: (error: HttpErrorResponse) => {
        this.snackbar.openSnackBar('Error updating item', 'Close', true);
        console.error('Error updating item:', error);
      }
    });
  }

  onEditTodoItem(event: { id: number; name: string }) {
    if (event.name.trim().length === 0) {
      this.snackbar.openSnackBar('Todo item name cannot be only whitespace', 'Close', true);
      this.editingItemId.set(null);
      return;
    }

    this.dataSource.editItem(event.id, event.name).subscribe({
      next: () => {
        this.snackbar.openSnackBar('Item updated successfully', 'Close');
        this.items$.set(
          this.items$().map(i => 
            i.id === event.id ? { ...i, name: event.name } : i
          )
        );
        this.editingItemId.set(null);
      },
      error: (error: HttpErrorResponse) => {
        this.snackbar.openSnackBar('Error updating item', 'Close', true);
        console.error('Error editing item:', error);
      }
    });
  }

  onEditingTodoItemChange(id: number | null) {
    this.editingItemId.set(id);
  }

  resetTodoItemForm() : void {
    this.newTodoItemModel.set({
      name: ' ',
    });

    this.newTodoItemForm.name().markAsDirty()
  }

  // ========================================
  // Clipboard - Event Handlers
  // ========================================
  onClipboardChange(event: Event) {
    const selectElement = event.target as HTMLSelectElement;
    const clipboardId = Number(selectElement.value);
    this.selectClipboard(clipboardId);
  }

  onClipboardSelect(id: number) {
    this.selectClipboard(id);
  }

  onClipboardDelete(id: number) {
    const clipboard = this.clipboards$().find(c => c.id === id);
    const hasItems = this.selectedClipboardId() === id && this.items$().length > 0;
    const unfinishedCount = this.selectedClipboardId() === id ? this.unfinishedItemsCount() : 0;
    
    let message = 'Are you sure you want to delete this clipboard?';
    if (hasItems) {
      message = unfinishedCount > 0
        ? `Are you sure you want to delete this clipboard? All items in it will be deleted (${unfinishedCount} unfinished).`
        : 'Are you sure you want to delete this clipboard? All items in it will be deleted.';
    }
    
    if (!confirm(message)) {
      return;
    }

    this.dataSource.removeClipboard(id).subscribe({
      next: () => {
        this.snackbar.openSnackBar('Clipboard deleted successfully', 'Close');
        this.clipboards$.set(this.clipboards$().filter(c => c.id !== id));
        
        if (this.selectedClipboardId() === id) {
          const remainingClipboards = this.clipboards$();
          if (remainingClipboards.length > 0) {
            this.router.navigate(['/clipboard', remainingClipboards[0].id], {
              queryParams: { filter: this.filter(), page: 1 }
            });
          } else {
            this.router.navigate(['/']);
          }
        }
      },
      error: (error: HttpErrorResponse) => {
        this.snackbar.openSnackBar('Error deleting clipboard', 'Close', true);
        console.error('Error deleting clipboard:', error);
      }
    });
  }

  onClipboardEdit(event: { id: number; name: string }) {
    const { id, name: newName } = event;
    this.editedClipboardName.set(newName);
  }

  onClipboardNameChange(newName: string) {
    this.editedClipboardName.set(newName);
  }

  onEditingClipboardChange(id: number | null) {
    this.editingClipboardId.set(id);
    
    // Initialize the edited name when editing starts
    if (id !== null) {
      const clipboard = this.clipboards$().find(c => c.id === id);
      if (clipboard) {
        this.editedClipboardName.set(clipboard.name);
      }
    } else {
      this.editedClipboardName.set('');
    }
  }

  onSaveClipboard() {
    const editingId = this.editingClipboardId();
    if (editingId === null) return;
    
    const newName = this.editedClipboardName();
    if (!newName || newName.trim() === '') return;

    this.dataSource.editClipboard(editingId, newName).subscribe({
      next: () => {
        this.snackbar.openSnackBar('Clipboard updated successfully', 'Close');
        this.clipboards$.set(
          this.clipboards$().map(c => 
            c.id === editingId ? { ...c, name: newName } : c
          )
        );
        this.editingClipboardId.set(null);
        this.editedClipboardName.set('');
      },
      error: (error: HttpErrorResponse) => {
        this.snackbar.openSnackBar('Error updating clipboard', 'Close', true);
        console.error('Error editing clipboard:', error);
      }
    });
  }

  onAddClipboard(event: SubmitEvent) {
    event.preventDefault();
    
    if (this.newClipboardForm.name().invalid()) {
      this.newClipboardForm.name().markAsTouched();
      return;
    }

    const name = this.newClipboardForm.name().value();
    
    // Validate that the trimmed name is not empty
    if (name.trim().length === 0) {
      this.snackbar.openSnackBar('Clipboard name cannot be only whitespace', 'Close', true);
      return;
    }
    
    this.dataSource.addClipboard(name).subscribe({
      next: (clipboard: any) => {
        this.snackbar.openSnackBar('Clipboard added successfully', 'Close');
        this.clipboards$.set([...this.clipboards$(), clipboard]);
        this.resetClipboardForm();
        this.selectClipboard(clipboard.id);
      },
      error: (error: HttpErrorResponse) => {
        this.snackbar.openSnackBar('Error adding clipboard', 'Close', true);
        console.error('Error adding clipboard:', error);
      }
    });
  }

  resetClipboardForm(): void {
    this.newClipboardModel.set({
      name: ' ',
    });
    this.newClipboardForm.name().markAsDirty();
  }
}
