// Services/Web/React/todo/src/components/todo-item/todo-item.tsx
import { useState, useRef, useEffect } from 'react';
import './todo-item.css';
import CheckBoxIcon from '@mui/icons-material/CheckBox';
import CheckBoxOutlineBlankIcon from '@mui/icons-material/CheckBoxOutlineBlank';
import EditIcon from '@mui/icons-material/Edit';
import UndoIcon from '@mui/icons-material/Undo';
import DeleteIcon from '@mui/icons-material/Delete';

interface ITodoItem {
  id: number;
  clipboardId: number;
  name: string;
  isComplete: boolean;
}

interface TodoItemProps {
  item: ITodoItem;
  editingItemId: number | null;
  onComplete: (id: number) => void;
  onEdit: (id: number) => void;
  onCancelEdit: () => void;
  onSave: (id: number, name: string) => void;
  onDelete: (id: number) => void;
}

export function TodoItem({
  item,
  editingItemId,
  onComplete,
  onEdit,
  onCancelEdit,
  onSave,
  onDelete
}: TodoItemProps) {
  const [editedName, setEditedName] = useState(item.name);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const isEditing = editingItemId === item.id;

  useEffect(() => {
    setEditedName(item.name);
    if (isEditing && textareaRef.current) {
      textareaRef.current.focus();
      // Auto-resize textarea
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = textareaRef.current.scrollHeight + 'px';
    }
  }, [isEditing, item.name]);

  const handleTextChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setEditedName(e.target.value);
    // Auto-resize textarea
    e.target.style.height = 'auto';
    e.target.style.height = e.target.scrollHeight + 'px';
  };

  const handleEdit = () => {
    if (isEditing) {
      setEditedName(item.name);
      onCancelEdit();
    } else {
      onEdit(item.id);
    }
  };

  const handleSave = () => {
    onSave(item.id, editedName);
  };

  const handleComplete = () => {
    onComplete(item.id);
  };

  const handleDelete = () => {
    onDelete(item.id);
  };

  const className = `app-todo-item${item.isComplete ? ' completed' : ''}${isEditing ? ' editing' : ''}`;

  return (
    <div className={className}>
      <textarea
        ref={textareaRef}
        readOnly={!isEditing}
        value={isEditing ? editedName : item.name}
        onChange={handleTextChange}
      />
      <div className="button-group">
        <button onClick={handleComplete} disabled={isEditing} title="Mark as complete">
          {item.isComplete ? (
            <CheckBoxIcon />
          ) : (
            <CheckBoxOutlineBlankIcon />
          )}
        </button>
        <button onClick={handleEdit} disabled={editingItemId !== null && !isEditing || item.isComplete} title={isEditing ? 'Undo' : 'Edit'}>
          {isEditing ? (
            <UndoIcon />
          ) : (
            <EditIcon />
          )}
        </button>
        <button onClick={handleDelete} title="Delete">
          <DeleteIcon />
        </button>
      </div>
      {isEditing && (
        <button className="save-button" onClick={handleSave} disabled={editedName === item.name}>
          Save
        </button>
      )}
    </div>
  );
}

export default TodoItem;

// Services/Web/Angular/todo/src/app/components/todo-item/todo-item.ts
import { Component, input, output, ViewChild, ElementRef, AfterViewInit, effect, signal } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';

@Component({
  selector: 'app-todo-item',
  imports: [MatIconModule, MatButtonModule],
  templateUrl: './todo-item.html',
  styleUrl: './todo-item.css',
})
export class TodoItem implements AfterViewInit {
  id = input(0)
  name = input('');
  completed = input(false);
  editingItemId = input<number | null>(null);
  
  delete = output<number>();
  complete = output<number>();
  edit = output<{ id: number; name: string }>();
  editingChange = output<number | null>();

  isEditing = signal(false);
  editedName = signal('');

  @ViewChild('textarea') textarea?: ElementRef<HTMLTextAreaElement>;

  constructor() {
    effect(() => {
      this.name();
      setTimeout(() => this.adjustTextareaHeight(), 0);
    });
  }

  ngAfterViewInit() {
    this.adjustTextareaHeight();
  }

  adjustTextareaHeight() {
    if (this.textarea?.nativeElement) {
      const element = this.textarea.nativeElement;
      element.style.height = 'auto';
      element.style.height = element.scrollHeight + 'px';
    }
  }

  onEdit() {
    if (this.isEditing()) {
      this.editedName.set(this.name());
      this.isEditing.set(false);
      this.editingChange.emit(null);
    } else {
      this.editedName.set(this.name());
      this.isEditing.set(true);
      this.editingChange.emit(this.id());
      setTimeout(() => {
        if (this.textarea?.nativeElement) {
          this.textarea.nativeElement.focus();
        }
      }, 0);
    }
  }

  onTextChange(event: Event) {
    const target = event.target as HTMLTextAreaElement;
    this.editedName.set(target.value);
    this.adjustTextareaHeight();
  }

  onSave() {
    this.edit.emit({ id: this.id(), name: this.editedName() });
    this.isEditing.set(false);
  }

  onDelete() {
    this.delete.emit(this.id());
  }

  onComplete() {
    this.complete.emit(this.id());
  }
}
