// Services/Web/React/todo/src/components/clipboard-item/clipboard-item.tsx
import './clipboard-item.css';
import { useState, useRef, useEffect } from 'react';
import EditIcon from '@mui/icons-material/Edit';
import UndoIcon from '@mui/icons-material/Undo';
import DeleteIcon from '@mui/icons-material/Delete';

interface ClipboardItemProps {
  id: number;
  name: string;
  isSelected?: boolean;
  editingClipboardId: number | null;
  onDelete: (id: number) => void;
  onEditingChange: (id: number | null) => void;
  onNameChange: (id: number, name: string) => void;
}

export function ClipboardItem({
  id,
  name,
  isSelected = false,
  editingClipboardId,
  onDelete,
  onEditingChange,
  onNameChange
}: ClipboardItemProps) {
  const [isEditing, setIsEditing] = useState(false);
  const nameInputRef = useRef<HTMLInputElement>(null);

  // Sync local editing state with the parent's editingClipboardId
  useEffect(() => {
    if (editingClipboardId !== id && isEditing) {
      setIsEditing(false);
    }
  }, [editingClipboardId, id, isEditing]);

  const handleEdit = () => {
    // Start editing
    setIsEditing(true);
    onEditingChange(id);
    setTimeout(() => {
      if (nameInputRef.current) {
        nameInputRef.current.focus();
        nameInputRef.current.select();
      }
    }, 0);
  };

  const handleCancel = () => {
    setIsEditing(false);
    onEditingChange(null);
    if (nameInputRef.current) {
      nameInputRef.current.value = name;
    }
  };

  const handleDelete = () => {
    onDelete(id);
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Escape') {
      setIsEditing(false);
      onEditingChange(null);
      if (nameInputRef.current) {
        nameInputRef.current.value = name;
      }
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    onNameChange(id, e.target.value);
  };

  return (
    <div className={`clipboard-item${isSelected ? ' selected' : ''}${isEditing ? ' editing' : ''}`}>
      <div className="clipboard-content">
        <div className="clipboard-name-container">
          <input
            ref={nameInputRef}
            type="text"
            defaultValue={name}
            readOnly={!isEditing}
            className="clipboard-name"
            onKeyDown={handleKeyDown}
            onChange={handleChange}
          />
        </div>
        <div className="clipboard-actions">
          <button
            type="button"
            onClick={isEditing ? handleCancel : handleEdit}
            className="edit-btn"
            disabled={editingClipboardId !== null && editingClipboardId !== id}
          >
            {isEditing ? <UndoIcon /> : <EditIcon />}
          </button>
          <button
            type="button"
            onClick={handleDelete}
            className="delete-btn"
          >
            <DeleteIcon />
          </button>
        </div>
      </div>
    </div>
  );
}

// Services/Web/Angular/todo/src/app/components/clipboard-item/clipboard-item.ts
import { Component, input, output, signal, effect, ViewChild, ElementRef } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';

@Component({
  selector: 'app-clipboard-item',
  imports: [MatIconModule, MatButtonModule],
  templateUrl: './clipboard-item.html',
  styleUrl: './clipboard-item.css'
})
export class ClipboardItem {
  id = input(0);
  name = input('');
  isSelected = input(false);
  editingClipboardId = input<number | null>(null);
  
  select = output<number>();
  delete = output<number>();
  edit = output<{ id: number; name: string }>();
  editingChange = output<number | null>();
  nameChange = output<string>();

  isEditing = signal(false);
  editedName = signal('');

  @ViewChild('nameInput') nameInput?: ElementRef<HTMLInputElement>;

  constructor() {
    effect(() => {
      const editingId = this.editingClipboardId();
      if (editingId !== this.id() && this.isEditing()) {
        this.isEditing.set(false);
      }
    });
  }

  onEdit() {
    if (this.isEditing()) {
      // Revert/cancel
      this.editedName.set(this.name());
      this.isEditing.set(false);
      this.editingChange.emit(null);
      if (this.nameInput) {
        this.nameInput.nativeElement.readOnly = true;
      }
    } else {
      // Start editing
      this.editedName.set(this.name());
      this.isEditing.set(true);
      this.editingChange.emit(this.id());
      setTimeout(() => {
        if (this.nameInput) {
          this.nameInput.nativeElement.readOnly = false;
          this.nameInput.nativeElement.focus();
        }
      }, 0);
    }
  }

  onNameChange(event: Event) {
    const target = event.target as HTMLInputElement;
    const value = target.value;
    this.editedName.set(value);
    this.nameChange.emit(value);
  }

  onSave() {
    if (this.editedName().trim() && this.editedName() !== this.name()) {
      this.edit.emit({ id: this.id(), name: this.editedName() });
    }
    this.isEditing.set(false);
    this.editingChange.emit(null);
    if (this.nameInput) {
      this.nameInput.nativeElement.readOnly = true;
    }
  }

  onCancel() {
    this.editedName.set(this.name());
    this.isEditing.set(false);
    this.editingChange.emit(null);
    if (this.nameInput) {
      this.nameInput.nativeElement.readOnly = true;
    }
  }

  onDelete() {
    this.delete.emit(this.id());
  }

  onSelect() {
    if (!this.isEditing()) {
      this.select.emit(this.id());
    }
  }
}
